from dataclasses import dataclass
from datetime import datetime
from typing import Optional

@dataclass
class Event:
    """Base class for all system events in the message bus."""
    timestamp: datetime

@dataclass
class MarketTick(Event):
    """High-frequency orderbook update."""
    symbol: str
    bid: float
    ask: float
    bid_vol: float
    ask_vol: float

@dataclass
class ForecastUpdate(Event):
    """Weather or generation forecast revision."""
    zone: str
    delivery_time: datetime
    forecast_mw: float
    provider: str

@dataclass
class SignalEvent(Event):
    """Actionable trading signal generated by a model."""
    zone: str
    delivery_time: datetime
    signal_type: str  # e.g., "WIND_SHOCK"
    strength: float   # Normalized -1.0 (strong sell) to 1.0 (strong buy)

@dataclass
class OrderEvent(Event):
    """Execution order sent to the exchange/simulator."""
    order_id: str
    zone: str
    delivery_time: datetime
    side: str
    qty_mw: float
    price_limit: float
